# Generated by Django 3.2.8 on 2021-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(default=2, path='C:/Users/USER/Desktop/fitnfine/fitness/blog/static/img'),
            preserve_default=False,
        ),
    ]
