# Generated by Django 3.2.8 on 2021-12-26 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_statslogin_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time', models.DateTimeField(auto_now=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
