# Generated by Django 3.2.8 on 2021-12-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_weighttracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightTracker',
        ),
    ]
